FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.23-openshift-4.19 AS builder_rhel9
WORKDIR /go/src/github.com/openshift/oc-mirror
COPY . .
RUN DISABLE_CGO=1 CGO_ENABLED=0 make build

FROM quay.io/oc-mirror/integration-tests-artifacts:v0.0.1 as embedd

FROM registry.redhat.io/ubi9-minimal@sha256:30bbd445046a3a63f5f5557a3c67dee74e3c8e7855eb0347630b020f3689823f
COPY --from=builder_rhel9 /go/src/github.com/openshift/oc-mirror/v2/bin/oc-mirror /usr/bin/oc-mirror
RUN mkdir -p /artifacts/scripts && mkdir -p /artifacts/isc && mkdir -p /artifacts/workingdir && chmod -R 777 /artifacts
RUN mkdir -p /root/.docker
RUN mkdir -p /root/.oc-mirror/.cache

COPY --from=embedd artifacts/scripts /artifacts/scripts
COPY --from=embedd artifacts/isc /artifacts/isc
COPY --from=embedd artifacts/uid_entrypoint.sh /artifacts

WORKDIR /artifacts

LABEL io.k8s.display-name="oc-mirror-integrations-tests" \
      io.k8s.description="Integration tests for oc-mirror v2 plugin." \
      io.openshift.tags="cli,mirror" \
      maintainer="luzuccar@redhat.com"

ENTRYPOINT ["./uid_entrypoint.sh"]


