FROM registry.redhat.io/ubi9-minimal@sha256:30bbd445046a3a63f5f5557a3c67dee74e3c8e7855eb0347630b020f3689823f
RUN mkdir -p /artifacts/scripts && mkdir -p /artifacts/isc 
RUN chmod -R 755 /artifacts
COPY ./scripts /artifact/scripts
COPY ./isc /artifacts/isc
LABEL io.k8s.display-name="oc-mirror-integrations-tests-artifacts" \
      io.k8s.description="Integration tests for oc-mirror v2 plugin." \
      io.openshift.tags="cli,mirror" \
      maintainer="luzuccar@redhat.com"


