kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  platform:
    graph: true 
    architectures:
    - amd64
    channels:
    - name: stable-4.16
      minVersion: '4.16.1'
      maxVersion: '4.16.1'
      shortestPath: true
  helm:
    repositories:
    - name: sbo
      url: https://redhat-developer.github.io/service-binding-operator-helm-chart/
  additionalImages:
  - name: registry.redhat.io/ubi8/ubi:latest
  - name: quay.io/openshifttest/hello-openshift@sha256:61b8f5e1a3b5dbd9e2c35fd448dc5106337d7a299873dd3a6f0cd8d4891ecc27
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.16
    packages:
    - name: devworkspace-operator
